(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT! *)

type array_
type array_builder
type binary_array
type binary_array_builder
type binary_data_type
type boolean_array
type boolean_array_builder
type boolean_data_type
type buffer
type buffer_input_stream
type buffer_output_stream
type csv_read_options
type csv_reader
type cast_options
type chunked_array
type codec
type column
type compressed_input_stream
type compressed_output_stream
type count_options
type data_type
type date32_array
type date32_array_builder
type date32_data_type
type date64_array
type date64_array_builder
type date64_data_type
type decimal128
type decimal128_array
type decimal128_array_builder
type decimal128_data_type
type decimal_data_type
type dense_union_array
type dense_union_data_type
type dictionary_array
type dictionary_data_type
type double_array
type double_array_builder
type double_data_type
type feather_file_reader
type feather_file_writer
type field
type file_output_stream
type fixed_size_binary_array
type fixed_size_binary_data_type
type fixed_width_data_type
type float_array
type float_array_builder
type float_data_type
type floating_point_data_type
type gio_input_stream
type gio_output_stream
type input_stream
type int16_array
type int16_array_builder
type int16_data_type
type int32_array
type int32_array_builder
type int32_data_type
type int64_array
type int64_array_builder
type int64_data_type
type int8_array
type int8_array_builder
type int8_data_type
type int_array_builder
type integer_data_type
type list_array
type list_array_builder
type list_data_type
type memory_mapped_input_stream
type mutable_buffer
type null_array
type null_array_builder
type null_data_type
type numeric_array
type numeric_data_type
type output_stream
type primitive_array
type record_batch
type record_batch_builder
type record_batch_file_reader
type record_batch_file_writer
type record_batch_reader
type record_batch_stream_reader
type record_batch_stream_writer
type record_batch_writer
type resizable_buffer
type schema
type seekable_input_stream
type sparse_union_array
type sparse_union_data_type
type string_array
type string_array_builder
type string_data_type
type struct_array
type struct_array_builder
type struct_data_type
type table
type table_batch_reader
type tensor
type time32_array
type time32_array_builder
type time32_data_type
type time64_array
type time64_array_builder
type time64_data_type
type time_data_type
type timestamp_array
type timestamp_array_builder
type timestamp_data_type
type u_int16_array
type u_int16_array_builder
type u_int16_data_type
type u_int32_array
type u_int32_array_builder
type u_int32_data_type
type u_int64_array
type u_int64_array_builder
type u_int64_data_type
type u_int8_array
type u_int8_array_builder
type u_int8_data_type
type u_int_array_builder
type union_array
type union_data_type

module Array : sig
  type t = array_
end

module ArrayBuilder : sig
  type t = array_builder
end

module BinaryArray : sig
  type t = binary_array
end

module BinaryArrayBuilder : sig
  type t = binary_array_builder
end

module BinaryDataType : sig
  type t = binary_data_type
end

module BooleanArray : sig
  type t = boolean_array
end

module BooleanArrayBuilder : sig
  type t = boolean_array_builder
end

module BooleanDataType : sig
  type t = boolean_data_type
end

module Buffer : sig
  type t = buffer
end

module BufferInputStream : sig
  type t = buffer_input_stream
end

module BufferOutputStream : sig
  type t = buffer_output_stream
end

module CSVReadOptions : sig
  type t = csv_read_options
end

module CSVReader : sig
  type t = csv_reader
end

module CastOptions : sig
  type t = cast_options
end

module ChunkedArray : sig
  type t = chunked_array
end

module Codec : sig
  type t = codec
end

module Column : sig
  type t = column
end

module CompressedInputStream : sig
  type t = compressed_input_stream
end

module CompressedOutputStream : sig
  type t = compressed_output_stream
end

module CountOptions : sig
  type t = count_options
end

module DataType : sig
  type t = data_type
end

module Date32Array : sig
  type t = date32_array
end

module Date32ArrayBuilder : sig
  type t = date32_array_builder
end

module Date32DataType : sig
  type t = date32_data_type
end

module Date64Array : sig
  type t = date64_array
end

module Date64ArrayBuilder : sig
  type t = date64_array_builder
end

module Date64DataType : sig
  type t = date64_data_type
end

module Decimal128 : sig
  type t = decimal128
end

module Decimal128Array : sig
  type t = decimal128_array
end

module Decimal128ArrayBuilder : sig
  type t = decimal128_array_builder
end

module Decimal128DataType : sig
  type t = decimal128_data_type
end

module DecimalDataType : sig
  type t = decimal_data_type
end

module DenseUnionArray : sig
  type t = dense_union_array
end

module DenseUnionDataType : sig
  type t = dense_union_data_type
end

module DictionaryArray : sig
  type t = dictionary_array
end

module DictionaryDataType : sig
  type t = dictionary_data_type
end

module DoubleArray : sig
  type t = double_array
end

module DoubleArrayBuilder : sig
  type t = double_array_builder
end

module DoubleDataType : sig
  type t = double_data_type
end

module FeatherFileReader : sig
  type t = feather_file_reader
end

module FeatherFileWriter : sig
  type t = feather_file_writer
end

module Field : sig
  type t = field
end

module FileOutputStream : sig
  type t = file_output_stream
end

module FixedSizeBinaryArray : sig
  type t = fixed_size_binary_array
end

module FixedSizeBinaryDataType : sig
  type t = fixed_size_binary_data_type
end

module FixedWidthDataType : sig
  type t = fixed_width_data_type
end

module FloatArray : sig
  type t = float_array
end

module FloatArrayBuilder : sig
  type t = float_array_builder
end

module FloatDataType : sig
  type t = float_data_type
end

module FloatingPointDataType : sig
  type t = floating_point_data_type
end

module GIOInputStream : sig
  type t = gio_input_stream
end

module GIOOutputStream : sig
  type t = gio_output_stream
end

module InputStream : sig
  type t = input_stream
end

module Int16Array : sig
  type t = int16_array
end

module Int16ArrayBuilder : sig
  type t = int16_array_builder
end

module Int16DataType : sig
  type t = int16_data_type
end

module Int32Array : sig
  type t = int32_array
end

module Int32ArrayBuilder : sig
  type t = int32_array_builder
end

module Int32DataType : sig
  type t = int32_data_type
end

module Int64Array : sig
  type t = int64_array
end

module Int64ArrayBuilder : sig
  type t = int64_array_builder
end

module Int64DataType : sig
  type t = int64_data_type
end

module Int8Array : sig
  type t = int8_array
end

module Int8ArrayBuilder : sig
  type t = int8_array_builder
end

module Int8DataType : sig
  type t = int8_data_type
end

module IntArrayBuilder : sig
  type t = int_array_builder
end

module IntegerDataType : sig
  type t = integer_data_type
end

module ListArray : sig
  type t = list_array
end

module ListArrayBuilder : sig
  type t = list_array_builder
end

module ListDataType : sig
  type t = list_data_type
end

module MemoryMappedInputStream : sig
  type t = memory_mapped_input_stream
end

module MutableBuffer : sig
  type t = mutable_buffer
end

module NullArray : sig
  type t = null_array
end

module NullArrayBuilder : sig
  type t = null_array_builder
end

module NullDataType : sig
  type t = null_data_type
end

module NumericArray : sig
  type t = numeric_array
end

module NumericDataType : sig
  type t = numeric_data_type
end

module OutputStream : sig
  type t = output_stream
end

module PrimitiveArray : sig
  type t = primitive_array
end

module RecordBatch : sig
  type t = record_batch
end

module RecordBatchBuilder : sig
  type t = record_batch_builder
end

module RecordBatchFileReader : sig
  type t = record_batch_file_reader
end

module RecordBatchFileWriter : sig
  type t = record_batch_file_writer
end

module RecordBatchReader : sig
  type t = record_batch_reader
end

module RecordBatchStreamReader : sig
  type t = record_batch_stream_reader
end

module RecordBatchStreamWriter : sig
  type t = record_batch_stream_writer
end

module RecordBatchWriter : sig
  type t = record_batch_writer
end

module ResizableBuffer : sig
  type t = resizable_buffer
end

module Schema : sig
  type t = schema
end

module SeekableInputStream : sig
  type t = seekable_input_stream
end

module SparseUnionArray : sig
  type t = sparse_union_array
end

module SparseUnionDataType : sig
  type t = sparse_union_data_type
end

module StringArray : sig
  type t = string_array
end

module StringArrayBuilder : sig
  type t = string_array_builder
end

module StringDataType : sig
  type t = string_data_type
end

module StructArray : sig
  type t = struct_array
end

module StructArrayBuilder : sig
  type t = struct_array_builder
end

module StructDataType : sig
  type t = struct_data_type
end

module Table : sig
  type t = table
end

module TableBatchReader : sig
  type t = table_batch_reader
end

module Tensor : sig
  type t = tensor
end

module Time32Array : sig
  type t = time32_array
end

module Time32ArrayBuilder : sig
  type t = time32_array_builder
end

module Time32DataType : sig
  type t = time32_data_type
end

module Time64Array : sig
  type t = time64_array
end

module Time64ArrayBuilder : sig
  type t = time64_array_builder
end

module Time64DataType : sig
  type t = time64_data_type
end

module TimeDataType : sig
  type t = time_data_type
end

module TimestampArray : sig
  type t = timestamp_array
end

module TimestampArrayBuilder : sig
  type t = timestamp_array_builder
end

module TimestampDataType : sig
  type t = timestamp_data_type
end

module UInt16Array : sig
  type t = u_int16_array
end

module UInt16ArrayBuilder : sig
  type t = u_int16_array_builder
end

module UInt16DataType : sig
  type t = u_int16_data_type
end

module UInt32Array : sig
  type t = u_int32_array
end

module UInt32ArrayBuilder : sig
  type t = u_int32_array_builder
end

module UInt32DataType : sig
  type t = u_int32_data_type
end

module UInt64Array : sig
  type t = u_int64_array
end

module UInt64ArrayBuilder : sig
  type t = u_int64_array_builder
end

module UInt64DataType : sig
  type t = u_int64_data_type
end

module UInt8Array : sig
  type t = u_int8_array
end

module UInt8ArrayBuilder : sig
  type t = u_int8_array_builder
end

module UInt8DataType : sig
  type t = u_int8_data_type
end

module UIntArrayBuilder : sig
  type t = u_int_array_builder
end

module UnionArray : sig
  type t = union_array
end

module UnionDataType : sig
  type t = union_data_type
end

