(* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT! *)

module C = Arrow_bindings.C (Arrow_generated)
type array_ = C.array_
type array_builder = C.array_builder
type binary_array = C.binary_array
type binary_array_builder = C.binary_array_builder
type binary_data_type = C.binary_data_type
type boolean_array = C.boolean_array
type boolean_array_builder = C.boolean_array_builder
type boolean_data_type = C.boolean_data_type
type buffer = C.buffer
type buffer_input_stream = C.buffer_input_stream
type buffer_output_stream = C.buffer_output_stream
type csv_read_options = C.csv_read_options
type csv_reader = C.csv_reader
type cast_options = C.cast_options
type chunked_array = C.chunked_array
type codec = C.codec
type column = C.column
type compressed_input_stream = C.compressed_input_stream
type compressed_output_stream = C.compressed_output_stream
type count_options = C.count_options
type data_type = C.data_type
type date32_array = C.date32_array
type date32_array_builder = C.date32_array_builder
type date32_data_type = C.date32_data_type
type date64_array = C.date64_array
type date64_array_builder = C.date64_array_builder
type date64_data_type = C.date64_data_type
type decimal128 = C.decimal128
type decimal128_array = C.decimal128_array
type decimal128_array_builder = C.decimal128_array_builder
type decimal128_data_type = C.decimal128_data_type
type decimal_data_type = C.decimal_data_type
type dense_union_array = C.dense_union_array
type dense_union_data_type = C.dense_union_data_type
type dictionary_array = C.dictionary_array
type dictionary_data_type = C.dictionary_data_type
type double_array = C.double_array
type double_array_builder = C.double_array_builder
type double_data_type = C.double_data_type
type feather_file_reader = C.feather_file_reader
type feather_file_writer = C.feather_file_writer
type field = C.field
type file_output_stream = C.file_output_stream
type fixed_size_binary_array = C.fixed_size_binary_array
type fixed_size_binary_data_type = C.fixed_size_binary_data_type
type fixed_width_data_type = C.fixed_width_data_type
type float_array = C.float_array
type float_array_builder = C.float_array_builder
type float_data_type = C.float_data_type
type floating_point_data_type = C.floating_point_data_type
type gio_input_stream = C.gio_input_stream
type gio_output_stream = C.gio_output_stream
type input_stream = C.input_stream
type int16_array = C.int16_array
type int16_array_builder = C.int16_array_builder
type int16_data_type = C.int16_data_type
type int32_array = C.int32_array
type int32_array_builder = C.int32_array_builder
type int32_data_type = C.int32_data_type
type int64_array = C.int64_array
type int64_array_builder = C.int64_array_builder
type int64_data_type = C.int64_data_type
type int8_array = C.int8_array
type int8_array_builder = C.int8_array_builder
type int8_data_type = C.int8_data_type
type int_array_builder = C.int_array_builder
type integer_data_type = C.integer_data_type
type list_array = C.list_array
type list_array_builder = C.list_array_builder
type list_data_type = C.list_data_type
type memory_mapped_input_stream = C.memory_mapped_input_stream
type mutable_buffer = C.mutable_buffer
type null_array = C.null_array
type null_array_builder = C.null_array_builder
type null_data_type = C.null_data_type
type numeric_array = C.numeric_array
type numeric_data_type = C.numeric_data_type
type output_stream = C.output_stream
type primitive_array = C.primitive_array
type record_batch = C.record_batch
type record_batch_builder = C.record_batch_builder
type record_batch_file_reader = C.record_batch_file_reader
type record_batch_file_writer = C.record_batch_file_writer
type record_batch_reader = C.record_batch_reader
type record_batch_stream_reader = C.record_batch_stream_reader
type record_batch_stream_writer = C.record_batch_stream_writer
type record_batch_writer = C.record_batch_writer
type resizable_buffer = C.resizable_buffer
type schema = C.schema
type seekable_input_stream = C.seekable_input_stream
type sparse_union_array = C.sparse_union_array
type sparse_union_data_type = C.sparse_union_data_type
type string_array = C.string_array
type string_array_builder = C.string_array_builder
type string_data_type = C.string_data_type
type struct_array = C.struct_array
type struct_array_builder = C.struct_array_builder
type struct_data_type = C.struct_data_type
type table = C.table
type table_batch_reader = C.table_batch_reader
type tensor = C.tensor
type time32_array = C.time32_array
type time32_array_builder = C.time32_array_builder
type time32_data_type = C.time32_data_type
type time64_array = C.time64_array
type time64_array_builder = C.time64_array_builder
type time64_data_type = C.time64_data_type
type time_data_type = C.time_data_type
type timestamp_array = C.timestamp_array
type timestamp_array_builder = C.timestamp_array_builder
type timestamp_data_type = C.timestamp_data_type
type u_int16_array = C.u_int16_array
type u_int16_array_builder = C.u_int16_array_builder
type u_int16_data_type = C.u_int16_data_type
type u_int32_array = C.u_int32_array
type u_int32_array_builder = C.u_int32_array_builder
type u_int32_data_type = C.u_int32_data_type
type u_int64_array = C.u_int64_array
type u_int64_array_builder = C.u_int64_array_builder
type u_int64_data_type = C.u_int64_data_type
type u_int8_array = C.u_int8_array
type u_int8_array_builder = C.u_int8_array_builder
type u_int8_data_type = C.u_int8_data_type
type u_int_array_builder = C.u_int_array_builder
type union_array = C.union_array
type union_data_type = C.union_data_type

module Array = struct
  type t = array_
end

module ArrayBuilder = struct
  type t = array_builder
end

module BinaryArray = struct
  type t = binary_array
end

module BinaryArrayBuilder = struct
  type t = binary_array_builder
end

module BinaryDataType = struct
  type t = binary_data_type
end

module BooleanArray = struct
  type t = boolean_array
end

module BooleanArrayBuilder = struct
  type t = boolean_array_builder
end

module BooleanDataType = struct
  type t = boolean_data_type
end

module Buffer = struct
  type t = buffer
end

module BufferInputStream = struct
  type t = buffer_input_stream
end

module BufferOutputStream = struct
  type t = buffer_output_stream
end

module CSVReadOptions = struct
  type t = csv_read_options
end

module CSVReader = struct
  type t = csv_reader
end

module CastOptions = struct
  type t = cast_options
end

module ChunkedArray = struct
  type t = chunked_array
end

module Codec = struct
  type t = codec
end

module Column = struct
  type t = column
end

module CompressedInputStream = struct
  type t = compressed_input_stream
end

module CompressedOutputStream = struct
  type t = compressed_output_stream
end

module CountOptions = struct
  type t = count_options
end

module DataType = struct
  type t = data_type
end

module Date32Array = struct
  type t = date32_array
end

module Date32ArrayBuilder = struct
  type t = date32_array_builder
end

module Date32DataType = struct
  type t = date32_data_type
end

module Date64Array = struct
  type t = date64_array
end

module Date64ArrayBuilder = struct
  type t = date64_array_builder
end

module Date64DataType = struct
  type t = date64_data_type
end

module Decimal128 = struct
  type t = decimal128
end

module Decimal128Array = struct
  type t = decimal128_array
end

module Decimal128ArrayBuilder = struct
  type t = decimal128_array_builder
end

module Decimal128DataType = struct
  type t = decimal128_data_type
end

module DecimalDataType = struct
  type t = decimal_data_type
end

module DenseUnionArray = struct
  type t = dense_union_array
end

module DenseUnionDataType = struct
  type t = dense_union_data_type
end

module DictionaryArray = struct
  type t = dictionary_array
end

module DictionaryDataType = struct
  type t = dictionary_data_type
end

module DoubleArray = struct
  type t = double_array
end

module DoubleArrayBuilder = struct
  type t = double_array_builder
end

module DoubleDataType = struct
  type t = double_data_type
end

module FeatherFileReader = struct
  type t = feather_file_reader
end

module FeatherFileWriter = struct
  type t = feather_file_writer
end

module Field = struct
  type t = field
end

module FileOutputStream = struct
  type t = file_output_stream
end

module FixedSizeBinaryArray = struct
  type t = fixed_size_binary_array
end

module FixedSizeBinaryDataType = struct
  type t = fixed_size_binary_data_type
end

module FixedWidthDataType = struct
  type t = fixed_width_data_type
end

module FloatArray = struct
  type t = float_array
end

module FloatArrayBuilder = struct
  type t = float_array_builder
end

module FloatDataType = struct
  type t = float_data_type
end

module FloatingPointDataType = struct
  type t = floating_point_data_type
end

module GIOInputStream = struct
  type t = gio_input_stream
end

module GIOOutputStream = struct
  type t = gio_output_stream
end

module InputStream = struct
  type t = input_stream
end

module Int16Array = struct
  type t = int16_array
end

module Int16ArrayBuilder = struct
  type t = int16_array_builder
end

module Int16DataType = struct
  type t = int16_data_type
end

module Int32Array = struct
  type t = int32_array
end

module Int32ArrayBuilder = struct
  type t = int32_array_builder
end

module Int32DataType = struct
  type t = int32_data_type
end

module Int64Array = struct
  type t = int64_array
end

module Int64ArrayBuilder = struct
  type t = int64_array_builder
end

module Int64DataType = struct
  type t = int64_data_type
end

module Int8Array = struct
  type t = int8_array
end

module Int8ArrayBuilder = struct
  type t = int8_array_builder
end

module Int8DataType = struct
  type t = int8_data_type
end

module IntArrayBuilder = struct
  type t = int_array_builder
end

module IntegerDataType = struct
  type t = integer_data_type
end

module ListArray = struct
  type t = list_array
end

module ListArrayBuilder = struct
  type t = list_array_builder
end

module ListDataType = struct
  type t = list_data_type
end

module MemoryMappedInputStream = struct
  type t = memory_mapped_input_stream
end

module MutableBuffer = struct
  type t = mutable_buffer
end

module NullArray = struct
  type t = null_array
end

module NullArrayBuilder = struct
  type t = null_array_builder
end

module NullDataType = struct
  type t = null_data_type
end

module NumericArray = struct
  type t = numeric_array
end

module NumericDataType = struct
  type t = numeric_data_type
end

module OutputStream = struct
  type t = output_stream
end

module PrimitiveArray = struct
  type t = primitive_array
end

module RecordBatch = struct
  type t = record_batch
end

module RecordBatchBuilder = struct
  type t = record_batch_builder
end

module RecordBatchFileReader = struct
  type t = record_batch_file_reader
end

module RecordBatchFileWriter = struct
  type t = record_batch_file_writer
end

module RecordBatchReader = struct
  type t = record_batch_reader
end

module RecordBatchStreamReader = struct
  type t = record_batch_stream_reader
end

module RecordBatchStreamWriter = struct
  type t = record_batch_stream_writer
end

module RecordBatchWriter = struct
  type t = record_batch_writer
end

module ResizableBuffer = struct
  type t = resizable_buffer
end

module Schema = struct
  type t = schema
end

module SeekableInputStream = struct
  type t = seekable_input_stream
end

module SparseUnionArray = struct
  type t = sparse_union_array
end

module SparseUnionDataType = struct
  type t = sparse_union_data_type
end

module StringArray = struct
  type t = string_array
end

module StringArrayBuilder = struct
  type t = string_array_builder
end

module StringDataType = struct
  type t = string_data_type
end

module StructArray = struct
  type t = struct_array
end

module StructArrayBuilder = struct
  type t = struct_array_builder
end

module StructDataType = struct
  type t = struct_data_type
end

module Table = struct
  type t = table
end

module TableBatchReader = struct
  type t = table_batch_reader
end

module Tensor = struct
  type t = tensor
end

module Time32Array = struct
  type t = time32_array
end

module Time32ArrayBuilder = struct
  type t = time32_array_builder
end

module Time32DataType = struct
  type t = time32_data_type
end

module Time64Array = struct
  type t = time64_array
end

module Time64ArrayBuilder = struct
  type t = time64_array_builder
end

module Time64DataType = struct
  type t = time64_data_type
end

module TimeDataType = struct
  type t = time_data_type
end

module TimestampArray = struct
  type t = timestamp_array
end

module TimestampArrayBuilder = struct
  type t = timestamp_array_builder
end

module TimestampDataType = struct
  type t = timestamp_data_type
end

module UInt16Array = struct
  type t = u_int16_array
end

module UInt16ArrayBuilder = struct
  type t = u_int16_array_builder
end

module UInt16DataType = struct
  type t = u_int16_data_type
end

module UInt32Array = struct
  type t = u_int32_array
end

module UInt32ArrayBuilder = struct
  type t = u_int32_array_builder
end

module UInt32DataType = struct
  type t = u_int32_data_type
end

module UInt64Array = struct
  type t = u_int64_array
end

module UInt64ArrayBuilder = struct
  type t = u_int64_array_builder
end

module UInt64DataType = struct
  type t = u_int64_data_type
end

module UInt8Array = struct
  type t = u_int8_array
end

module UInt8ArrayBuilder = struct
  type t = u_int8_array_builder
end

module UInt8DataType = struct
  type t = u_int8_data_type
end

module UIntArrayBuilder = struct
  type t = u_int_array_builder
end

module UnionArray = struct
  type t = union_array
end

module UnionDataType = struct
  type t = union_data_type
end

